# Generated by Django 5.2.13 on 2026-05-01 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_recordaccess'),
        ('workflows', '0004_accessrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleterequest',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.record'),
        ),
    ]
