# Generated by Django 5.2.13 on 2026-07-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_creationrequest_editrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='creationrequest',
            name='record_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='creationrequest',
            name='record_public_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deleterequest',
            name='record_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deleterequest',
            name='record_public_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='editrequest',
            name='record_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='editrequest',
            name='record_public_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
