# Generated by Django 5.2.13 on 2026-07-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0008_clarificationmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='clarificationmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
