# Generated by Django 5.2.13 on 2026-07-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0009_clarificationmessage_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='creationrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='deleterequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='editrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='rolechangerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10),
        ),
    ]
