# Generated by Django 5.2.13 on 2026-04-23 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0002_recordaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('USER_CREATED', 'User Created'), ('RECORD_CREATED', 'Record Created'), ('RECORD_UPDATED', 'Record Updated'), ('DELETION_REQUEST', 'Deletion Request'), ('DELETION_APPROVED', 'Deletion Approved'), ('DELETION_REJECTED', 'Deletion Rejected'), ('ROLE_CHANGE', 'Role Change Request')], max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.record')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
