# Generated by Django 5.2.13 on 2026-06-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_company_name_user_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('COLLABORATOR', 'Collaborator'), ('VIEWER', 'Viewer'), ('COMPLIANCE_OFFICER', 'Compliance Officer')], default='VIEWER', max_length=20),
        ),
    ]
