# Generated by Django 5.2.13 on 2026-07-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_failedloginattempt_mfachallenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_blacklisted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('COLLABORATOR', 'Collaborator'), ('VIEWER', 'Viewer'), ('COMPLIANCE_OFFICER', 'Compliance Officer')], db_index=True, default='VIEWER', max_length=20),
        ),
    ]
