# Generated by Django 5.2.13 on 2026-04-23 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('VIEW', 'View Only'), ('EDIT', 'Edit Access')], default='VIEW', max_length=10)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_assigned', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='records.record')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'record')},
            },
        ),
    ]
