# Generated by Django 5.2.13 on 2026-06-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_recordaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('PENDING_CREATION', 'Pending Creation'), ('APPROVED', 'Approved'), ('PENDING_EDITION', 'Pending Edition'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=20),
        ),
    ]
