# Generated by Django 5.2.13 on 2026-07-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_record_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='disclosure_department',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='disclosure_designation',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
