# Generated by Django 5.2.13 on 2026-07-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_record_disclosure_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='pan',
            field=models.CharField(max_length=255),
        ),
    ]
