# Generated by Django 5.2.13 on 2026-07-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_alter_record_pan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('PENDING_CREATION', 'Pending Creation'), ('APPROVED', 'Approved'), ('PENDING_EDITION', 'Pending Edition'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING_CREATION', max_length=20),
        ),
    ]
